<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ModeDetermination\" />
    <None Remove="AverageTemperature\" />
    <None Remove="RegulatorFactory\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="ModeDetermination\" />
    <Folder Include="AverageTemperature\" />
    <Folder Include="RegulatorFactory\" />
  </ItemGroup>
</Project>
