<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PomocneMetode\" />
    <None Remove="Repositories\" />
    <None Remove="Repositories\DeviceRepositories\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Repositories\" />
    <Folder Include="Repositories\DeviceRepositories\" />
  </ItemGroup>
</Project>
