<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Helpers\Helpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="HeaterServices\" />
    <None Remove="DeviceServices\" />
    <None Remove="LoggerServices\" />
    <None Remove="RegulatorServices\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="HeaterServices\" />
    <Folder Include="DeviceServices\" />
    <Folder Include="LoggerServices\" />
    <Folder Include="RegulatorServices\" />
  </ItemGroup>
</Project>
